Algoritmo "Matrizes"

Var
   Mat : vetor [1..3, 1..2] de Inteiro
   l, c : inteiro
Inicio
      Para l <- 1 ate 3 faca
           Para c <- 1 ate 2 faca
                Escreva ("Digite um valor : ")
                leia (Mat [l,c])
           FimPara
      FimPara
      
      Para l <- 1 ate 3 faca
           Para c <- 1 ate 2 faca
                Escreva ( Mat [l,c]:5)
           FimPara
           Escreval()
      FimPara

Fimalgoritmo